//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StickyFocusTarget.Localisation {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Loc {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Loc() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("StickyFocusTarget.Localisation.Loc", typeof(Loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string command_description_short {
            get {
                return ResourceManager.GetString("command_description_short", resourceCulture);
            }
        }
        
        internal static string command_description_long {
            get {
                return ResourceManager.GetString("command_description_long", resourceCulture);
            }
        }
        
        internal static string announcement_unchanged_pvp {
            get {
                return ResourceManager.GetString("announcement_unchanged_pvp", resourceCulture);
            }
        }
        
        internal static string announcement_changed {
            get {
                return ResourceManager.GetString("announcement_changed", resourceCulture);
            }
        }
        
        internal static string announcement_unchanged {
            get {
                return ResourceManager.GetString("announcement_unchanged", resourceCulture);
            }
        }
        
        internal static string settings_lang_dropdown_auto {
            get {
                return ResourceManager.GetString("settings_lang_dropdown_auto", resourceCulture);
            }
        }
        
        internal static string settings_lang_contribute_tooltip {
            get {
                return ResourceManager.GetString("settings_lang_contribute_tooltip", resourceCulture);
            }
        }
        
        internal static string settings_lang_contribute_button {
            get {
                return ResourceManager.GetString("settings_lang_contribute_button", resourceCulture);
            }
        }
        
        internal static string settings_lang_dropdown_label {
            get {
                return ResourceManager.GetString("settings_lang_dropdown_label", resourceCulture);
            }
        }
        
        internal static string settings_chat_announce_title {
            get {
                return ResourceManager.GetString("settings_chat_announce_title", resourceCulture);
            }
        }
        
        internal static string settings_chat_announce_do_not {
            get {
                return ResourceManager.GetString("settings_chat_announce_do_not", resourceCulture);
            }
        }
        
        internal static string settings_chat_announce_yes_if_changed {
            get {
                return ResourceManager.GetString("settings_chat_announce_yes_if_changed", resourceCulture);
            }
        }
        
        internal static string settings_chat_announce_yes_if_not_changed {
            get {
                return ResourceManager.GetString("settings_chat_announce_yes_if_not_changed", resourceCulture);
            }
        }
        
        internal static string settings_disable_in_pvp {
            get {
                return ResourceManager.GetString("settings_disable_in_pvp", resourceCulture);
            }
        }
        
        internal static string settings_commands_title {
            get {
                return ResourceManager.GetString("settings_commands_title", resourceCulture);
            }
        }
        
        internal static string settings_lang_credits {
            get {
                return ResourceManager.GetString("settings_lang_credits", resourceCulture);
            }
        }
    }
}
